name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'  # Run tests and push Docker image on tag

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t dotanr/user-management-service:${{ github.ref_name }} .

      # Push the Docker image
      - name: Push Docker image
        run: docker push dotanr/user-management-service:${{ github.ref_name }}